from enum import StrEnum
from pydantic import Field
from cumulus_library_pcx.llm.models.base import SpanAugmentedMention

# ---------------------------------------------------------------------------
# Shared enums
# ---------------------------------------------------------------------------
class LabInterpretation(StrEnum):
    """Interpretation flag aligned to HL7 v3 ObservationInterpretation
    (http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation).
    Shared by the instrument, clinician and LLM interpretation fields; provenance differs.
    LOW: below the reference range.
    NORMAL: within the reference range.
    HIGH: above the reference range.
    CRITICAL_LOW: below the critical low limit.
    CRITICAL_HIGH: above the critical high limit.
    ABNORMAL: abnormal without a stated direction.
    NOT_INTERPRETED: no interpretation available."""
    LOW = "LOW"
    NORMAL = "NORMAL"
    HIGH = "HIGH"
    CRITICAL_LOW = "CRITICAL_LOW"
    CRITICAL_HIGH = "CRITICAL_HIGH"
    ABNORMAL = "ABNORMAL"
    NOT_INTERPRETED = "NOT_INTERPRETED"

class LabInterpretationNormal(StrEnum):
    """Normality of a laboratory result.
    NORMAL: within the reference range.
    ABNORMAL: outside the reference range.
    NONE_OF_THE_ABOVE: normality not documented."""
    NORMAL = "NORMAL"
    ABNORMAL = "ABNORMAL"
    NONE_OF_THE_ABOVE = "NONE_OF_THE_ABOVE"

class LabTrend(StrEnum):
    """Clinician-documented trajectory of a laboratory result, as stated or clearly
    implied in the narrative. Never computed from serial values.
    IMPROVING: moving toward normal.
    WORSENING: moving away from normal.
    STABLE: unchanged.
    NORMALIZING: returned to or approaching the reference range.
    FLUCTUATING: rising and falling without a direction.
    NONE_OF_THE_ABOVE: None of the above."""
    IMPROVING = "IMPROVING"
    WORSENING = "WORSENING"
    STABLE = "STABLE"
    NORMALIZING = "NORMALIZING"
    FLUCTUATING = "FLUCTUATING"
    NONE_OF_THE_ABOVE = "NONE_OF_THE_ABOVE"

class LabValueType(StrEnum):
    """Representation of the reported laboratory value.
    ABSOLUTE: a numeric quantity or concentration.
    PERCENT: explicitly reported as a percentage.
    NONE_OF_THE_ABOVE: representation not determinable from the source."""
    ABSOLUTE = "ABSOLUTE"
    PERCENT = "PERCENT"
    NONE_OF_THE_ABOVE = "NONE_OF_THE_ABOVE"

# ---------------------------------------------------------------------------
# LabBaseMention
# ---------------------------------------------------------------------------
class LabBaseMention(SpanAugmentedMention):
    """
    Common fields for all analyte mentions. Value is captured as reported,
    with unit recorded verbatim from the source so downstream unit
    harmonization can operate on explicit provenance.
    """
    value_numeric: float | None = Field(
        default=None,
        description=(
            "Numeric value of the result as reported in the source. Capture "
            "the point estimate only; do not infer values from ranges or "
            "qualitative statements.")
    )
    value_type: LabValueType = Field(
        default=LabValueType.NONE_OF_THE_ABOVE,
        description=(
            "Representation of the reported value. Use ABSOLUTE when the result "
            "is reported as a numeric quantity or concentration. Use PERCENT only "
            "when the result is explicitly reported as a percentage or with the "
            "'%' symbol (e.g., neutrophils 62%, eosinophils 4%).")
    )
    value_unit: str | None = Field(
        default=None,
        description=(
            "Unit of measurement verbatim from the source (e.g., 'g/dL', "
            "'ng/mL', 'mg/L', 'ug/g', 'fL', 'x10^9/L'). Do not normalize.")
    )
    trend: LabTrend = Field(
        default=LabTrend.NONE_OF_THE_ABOVE,
        description=(
            "Physician-documented directional trajectory of this result as "
            "stated or clearly implied in clinical narrative. Capture only "
            "explicit clinician assertions about change over time (e.g., "
            "'hemoglobin improving', 'CRP continues to rise'). Do not infer "
            "trend from serial numeric values alone.")
    )
    interp_instrument: LabInterpretation = Field(
        default=LabInterpretation.NOT_INTERPRETED,
        description=(
            "Structured interpretation flag as printed on the lab report or "
            "generated by the lab instrument. Capture only when an explicit flag "
            "appears in the structured result header or result table; do not infer "
            "from the numeric value alone. Choose exactly one. "
            "LOW: flagged 'L' or 'Low'. "
            "NORMAL: flagged 'N' or 'Normal', or explicitly marked within range. "
            "HIGH: flagged 'H' or 'High'. "
            "CRITICAL_LOW: flagged 'LL', 'Critical Low' or a panic-low flag. "
            "CRITICAL_HIGH: flagged 'HH', 'Critical High' or a panic-high flag. "
            "ABNORMAL: flagged 'A' or 'Abnormal' with no direction. "
            "NOT_INTERPRETED: no flag is printed for this result.")
    )
    interp_clinician: LabInterpretation = Field(
        default=LabInterpretation.NOT_INTERPRETED,
        description=(
            "Clinician's qualitative assessment of the result as stated in the "
            "clinical narrative. Capture only explicit clinician assertions; do not "
            "infer from the numeric value alone. Choose exactly one. "
            "LOW: stated as low, decreased or below range (e.g., 'hemoglobin is low'). "
            "NORMAL: stated as normal or within normal limits (e.g., 'potassium within normal limits'). "
            "HIGH: stated as high, elevated or above range (e.g., 'CRP markedly elevated'). "
            "CRITICAL_LOW: stated as critically, dangerously or severely low. "
            "CRITICAL_HIGH: stated as critically, dangerously or severely high. "
            "ABNORMAL: stated as abnormal with no direction. "
            "NOT_INTERPRETED: the narrative reports the value without assessing it.")
    )
    interp_llm: LabInterpretation = Field(
        default=LabInterpretation.NOT_INTERPRETED,
        description=(
            "LLM best assertion of the result interpretation, synthesized from "
            "all available context: numeric value, unit, stated reference range, "
            "patient age, clinical narrative, and any implicit cues in the document. "
            "Apply general pediatric reference ranges when no explicit range is "
            "provided. This field may be populated even when interp_instrument "
            "and interp_clinician are absent. Choose exactly one. "
            "LOW: below the applicable reference range. "
            "NORMAL: within the applicable reference range. "
            "HIGH: above the applicable reference range. "
            "CRITICAL_LOW: below a critical low limit stated in the document or generally accepted for the analyte. "
            "CRITICAL_HIGH: above a critical high limit stated in the document or generally accepted for the analyte. "
            "ABNORMAL: abnormal but the direction cannot be determined (e.g., a qualitative result). "
            "NOT_INTERPRETED: only when insufficient context exists to make any reasonable determination.")
    )