[project]
name = "cumulus-library-pcx"
version = "0.3.0"
requires-python = ">=3.11"
dependencies = ["cumulus-study-builder>=0.5.0,<0.6", "cumulus-library>=6.3.4,<6.4"]
description = "PCX study on the shared Cumulus study builder."

[project.optional-dependencies]
test = ["pytest", "duckdb", "sqlglot", "PyYAML"]

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["cumulus_library_pcx*"]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
testpaths = ["tests"]
