"""
DuckDB test database: tests/data/schema.sql plus one CSV per table from a data directory,
then the study's hand-written SQL (custom/) and QA/WARN tables (tests/athena/).

Data directories:
    tests/data/warn         default: hand-written fixtures p1-p8, each seeded with anomalies
    tests/data/synthetic    generated by `make-pcx test-synthetic`. Only the schema.sql tables are
                            loaded, so its derived pcx__eligible* / pcx__outcome* CSVs are ignored
"""
import duckdb
from pathlib import Path
from cumulus_library_pcx.tools import filetool

SCHEMA = filetool.path_tests_data('schema.sql')

# custom/ SQL in dependency order
ELIGIBLE_OUTCOME = ['eligible_dx',
                    'eligible_surgery',
                    'eligible_rx',
                    'eligible_radiation',
                    'eligible',
                    'eligible_trial',
                    'outcome_vital_status',
                    'outcome_first_event',
                    'outcome_exposure',
                    'outcome']

def connect(data_dir: Path | None = None) -> duckdb.DuckDBPyConnection:
    """
    :param data_dir: directory of one CSV per schema.sql table, default tests/data/warn
    :return: connection with every table loaded (schema.sql types, CSV rows)
    """
    if data_dir is None:
        data_dir = filetool.path_tests_data_warn()
    con = duckdb.connect()
    con.execute("CREATE MACRO array_join(a, s) AS list_aggregate(a, 'string_agg', s)")
    con.execute(SCHEMA.read_text())
    for (table,) in con.execute('SHOW TABLES').fetchall():
        csv_file = data_dir / f'{table}.csv'
        if csv_file.exists():
            con.execute(f"COPY {table} FROM '{csv_file}' (HEADER, DELIMITER ',', NULLSTR '')")
    return con


def run_custom(con: duckdb.DuckDBPyConnection, names: list[str] = ELIGIBLE_OUTCOME) -> None:
    for name in names:
        con.execute(filetool.path_custom(f'pcx__{name}.sql').read_text())


def list_athena(pattern: str) -> list[Path]:
    """
    tests/athena/<pattern>.sql with the union table last (it reads the others).
    """
    files = sorted(filetool.path_tests_athena().glob(pattern))
    return [f for f in files if not f.stem.endswith('_union')] + [f for f in files if f.stem.endswith('_union')]


def run_athena(con: duckdb.DuckDBPyConnection, pattern: str) -> list[Path]:
    files = list_athena(pattern)
    for file in files:
        con.execute(file.read_text())
    return files
