[[actions]]
label = "case definition CSV upload"
type = "build:parallel"
files = [
    "../spreadsheet/file_upload_casedef.toml",
]

[[actions]]
label = "filter include/exclude"
type = "build:serial"
files = [
    "athena/pcx__cohort_casedef_candidate.sql",
    "athena/pcx__cohort_casedef_exclude.sql",
    "athena/pcx__cohort_casedef_include.sql",
]

[[actions]]
label = "cohort from case definition (valueset_casedef)"
type = "build:serial"
files = [
    "athena/pcx__cohort_casedef.sql",
]

[[actions]]
label = "cohort for case definition aspects (dx, rx, lab, proc)"
type = "build:serial"
files = [
    "athena/pcx__cohort_casedef_dx.sql",
    "athena/pcx__cohort_casedef_lab.sql",
    "athena/pcx__cohort_casedef_proc.sql",
    "athena/pcx__cohort_casedef_rx.sql",
]

[[actions]]
label = "timeline for casedef with variables"
type = "build:serial"
files = [
    "athena/pcx__cohort_timeline.sql",
]
