[[actions]]
description = "eligible criteria dx diagnosis"
type = "build:serial"
files = [
    "athena/pcx__eligible_dx_date.sql",
]

[[actions]]
description = "eligible criteria rx medications"
type = "build:serial"
files = [
    "athena/pcx__eligible_rx_date.sql",
    "athena/pcx__eligible_rx_date_evidence.sql",
    "athena/pcx__eligible_rx_date_prior_class.sql",
]

[[actions]]
description = "eligible criteria intersection"
type = "build:serial"
files = [
    "athena/pcx__eligible.sql",
]

[[actions]]
description = "eligible criteria minus gold verification"
type = "build:serial"
files = [
    "athena/pcx__eligible_dx_date_minus_gold.sql",
    "athena/pcx__eligible_dx_date_minus_gold_bins.sql",
    "athena/pcx__eligible_rx_date_minus_gold.sql",
    "athena/pcx__eligible_rx_date_minus_gold_bins.sql",
]
