[[actions]]
description = "outcome vital status, then first event, then exposure prior to first event"
type = "build:serial"
files = [
    "custom/pcx__outcome_vital_status.sql",
    "custom/pcx__outcome_first_event.sql",
    "custom/pcx__outcome_exposure.sql",
]

[[actions]]
description = "outcome per subject: overall survival and provisional event-free survival"
type = "build:serial"
files = [
    "custom/pcx__outcome.sql",
]
