[[actions]]
label = "casedef FHIR DocumentReference + FHIR DiagnosticReport"
type = "build:serial"
files = [
    "sql/generated/pcx__sample_casedef.sql",
]

[[actions]]
label = "calc 1x for each note_ref the note_author_date"
type = "build:serial"
files = [
    "sql/generated/pcx__sample_casedef_author.sql",
]

[[actions]]
label = "sample for aspects ('dx', 'lab', 'proc', 'rx')"
type = "build:parallel"
files = [
    "sql/generated/pcx__sample_casedef_dx.sql",
    "sql/generated/pcx__sample_casedef_lab.sql",
    "sql/generated/pcx__sample_casedef_proc.sql",
    "sql/generated/pcx__sample_casedef_rx.sql",
]

[[actions]]
label = "sample temporality ('pre', 'peri', 'peri_post', 'post')"
type = "build:parallel"
files = [
    "sql/generated/pcx__sample_casedef_pre.sql",
    "sql/generated/pcx__sample_casedef_peri.sql",
    "sql/generated/pcx__sample_casedef_peri_post.sql",
    "sql/generated/pcx__sample_casedef_post.sql",
]

[[actions]]
label = "sample size limit patients"
type = "build:parallel"
files = [
    "sql/generated/pcx__sample_casedef_pre_limit_patient_10.sql",
    "sql/generated/pcx__sample_casedef_peri_limit_patient_10.sql",
    "sql/generated/pcx__sample_casedef_peri_post_limit_patient_10.sql",
    "sql/generated/pcx__sample_casedef_post_limit_patient_10.sql",
]

[[actions]]
label = "sample size limit notes"
type = "build:parallel"
files = [
    "sql/generated/pcx__sample_casedef_pre_limit_note_50.sql",
    "sql/generated/pcx__sample_casedef_peri_limit_note_50.sql",
    "sql/generated/pcx__sample_casedef_peri_post_limit_note_50.sql",
    "sql/generated/pcx__sample_casedef_post_limit_note_50.sql",
]
