[[actions]]
description = "CSV valueset definitions for variables"
type = "build:parallel"
files = [
    "../spreadsheet/file_upload_study_variable.toml",
]

[[actions]]
description = "variable cohorts"
type = "build:parallel"
files = [
    "athena/pcx__cohort_dx_atrt.sql",
    "athena/pcx__cohort_dx_brain_cancer.sql",
    "athena/pcx__cohort_dx_medulloblastoma.sql",
    "athena/pcx__cohort_dx_methotrexate_toxic.sql",
    "athena/pcx__cohort_lab_absolute_neutrophil_count.sql",
    "athena/pcx__cohort_lab_alt.sql",
    "athena/pcx__cohort_lab_ast.sql",
    "athena/pcx__cohort_lab_creatinine.sql",
    "athena/pcx__cohort_lab_folate.sql",
    "athena/pcx__cohort_lab_folate_interpretation.sql",
    "athena/pcx__cohort_lab_folate_rbc.sql",
    "athena/pcx__cohort_lab_folate_unspecified.sql",
    "athena/pcx__cohort_lab_folate_whole_blood.sql",
    "athena/pcx__cohort_lab_hemoglobin.sql",
    "athena/pcx__cohort_lab_platelets.sql",
    "athena/pcx__cohort_lab_total_bilirubin.sql",
    "athena/pcx__cohort_rx_agent_carboplatin.sql",
    "athena/pcx__cohort_rx_agent_cisplatin.sql",
    "athena/pcx__cohort_rx_agent_cyclophosphamide.sql",
    "athena/pcx__cohort_rx_agent_etoposide.sql",
    "athena/pcx__cohort_rx_agent_methotrexate.sql",
    "athena/pcx__cohort_rx_agent_thiotepa.sql",
    "athena/pcx__cohort_rx_agent_vincristine.sql",
]
