[[actions]]
description = "inclusion/exclusion criteria for study population"
type = "build:parallel"
files = [
    "../spreadsheet/file_upload_population.toml",
]

[[actions]]
description = "study_period"
type = "build:parallel"
files = [
    "athena/pcx__cohort_study_period.sql",
]

[[actions]]
description = "study_population"
type = "build:parallel"
files = [
    "athena/pcx__cohort_study_population.sql",
]

[[actions]]
description = "obs_base, lab_base"
type = "build:serial"
files = [
    "athena/pcx__cohort_study_population_obs_base.sql",
    "athena/pcx__cohort_study_population_lab_base.sql",
]

[[actions]]
description = "study_population aspects ('enc', 'dx', 'rx', 'lab', 'proc', 'doc', 'diag', 'allergy')"
type = "build:parallel"
files = [
    "athena/pcx__cohort_study_population_enc.sql",
    "athena/pcx__cohort_study_population_dx.sql",
    "athena/pcx__cohort_study_population_rx.sql",
    "athena/pcx__cohort_study_population_lab.sql",
    "athena/pcx__cohort_study_population_proc.sql",
    "athena/pcx__cohort_study_population_doc.sql",
    "athena/pcx__cohort_study_population_diag.sql",
    "athena/pcx__cohort_study_population_allergy.sql",
]
