[[actions]]
label = "Shared and site-only counts"
type = "build:serial"
files = [
    "sql/generated/pcx__counts.workflow",
]
skip_by_default = true

[[actions]]
label = "Shared counts only"
type = "export:counts"
tables = [
    "sql/generated/pcx__counts.workflow",
]
skip_by_default = true
